version: '3.8'

services:
  picloud-db:
    image: postgres:15-alpine
    container_name: picloud-db
    environment:
      POSTGRES_USER: picloud
      POSTGRES_PASSWORD: Varunbike@1234
      POSTGRES_DB: picloud
    volumes:
      - picloud_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  picloud_db_data:
